version: '3.1'

services:

  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
